// SPDX-License-Identifier: GPL-2.0
/*
 * bd1860 lifted driver for UWS6152 (i2c@70500000 bd1860@40)
 *
 * Executes the stock W527 kernel's gxy_bd1860 driver + closed algorithm
 * (lifted machine code span [0x56c000,0x583200) from stock_Image) inside
 * our kernel. Blob + patch tables are generated by tools/gen_lift.py.
 *
 * Orchestration (ours, C):
 *   probe  -> arenas + patcher + input + thread + heartbp_init
 *   enable -> Sensor_Init(mode,led3) + Sensor_Start(mode,cfg3)
 *   thread -> Data_Read(mode,frame) every ~50ms; when frame full,
 *             health_pro(mode,0,NULL,frame,result) under kernel NEON,
 *             then report result[0..4] as REL 0..4 + sync (stock format)
 *   disable-> Sensor_Close()
 *
 * HAL contract unchanged: input/bd1860, hrenable, hrtest.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/i2c.h>
#include <linux/input.h>
#include <linux/device.h>
#include <linux/kthread.h>
#include <linux/delay.h>
#include <linux/mutex.h>
#include <linux/slab.h>
#include <linux/vmalloc.h>
#include <linux/mm.h>
#include <asm/neon.h>
#include <asm/cacheflush.h>

#define BD_SPAN_LO	0x0056c000

/* ---- API address table (index order must match BD_API_LIST order) ----
 * must be defined before including bd1860_blob.h, whose patch table
 * references these enum names. */
enum {
	BD_API___CONST_UDELAY = 0,
	BD_API___INIT_WAITQUEUE_HEAD,
	BD_API___STACK_CHK_FAIL,
	BD_API_COMPLETE,
	BD_API_DEV_ERR,
	BD_API_DEV_WARN,
	BD_API_I2C_RECOVER_BUS,
	BD_API_I2C_SMBUS_READ_I2C_BLOCK_DATA,
	BD_API_I2C_TRANSFER,
	BD_API_INPUT_EVENT,
	BD_API_KTHREAD_CREATE_ON_NODE,
	BD_API_KTHREAD_SHOULD_STOP,
	BD_API_KTHREAD_STOP,
	BD_API_MEMSET,
	BD_API_MSLEEP,
	BD_API_PRINTK,
	BD_API_USLEEP_RANGE,
	BD_API_WAKE_UP_PROCESS,
};

#include "bd1860_blob.h"

static void *bd_api_addrs[BD_API_MAX];

/* ---- runtime arenas ---- */
static void *bd_exec;
static unsigned long bd_exec_len;
static void *bd_ro;
static void *bd_bss;

static unsigned long bd_page_addr(u32 stock_page)
{
	int i;

	if (stock_page >= BD_LIFT_BLOB_OFF &&
	    stock_page < BD_LIFT_BLOB_OFF + BD_LIFT_BLOB_LEN)
		return (unsigned long)bd_exec + (stock_page - BD_LIFT_BLOB_OFF);
	for (i = 0; i < BD_RO_N; i++)
		if (bd_ro_stock_page[i] == stock_page)
			return (unsigned long)bd_ro + i * 4096;
	for (i = 0; i < BD_BSS_N; i++)
		if (bd_bss_stock_page[i] == stock_page)
			return (unsigned long)bd_bss + i * 4096;
	return 0;
}

static int bd_apply_patches(void)
{
	unsigned long tramp;
	int i;

	tramp = (unsigned long)bd_exec + ALIGN(BD_LIFT_BLOB_LEN, 8);
	for (i = 0; i < BD_API_MAX; i++) {
		u32 *stub = (u32 *)(tramp + i * 16);
		u64 addr = (u64)bd_api_addrs[i];

		stub[0] = 0x58000050;	/* ldr x16, [pc, #8] */
		stub[1] = 0xd61f0200;	/* br x16 */
		stub[2] = (u32)(addr & 0xffffffffu);
		stub[3] = (u32)(addr >> 32);
	}

	for (i = 0; i < ARRAY_SIZE(bd_lift_patches); i++) {
		u32 off = bd_lift_patches[i].off;
		u32 kind = bd_lift_patches[i].kind;
		u32 arg = bd_lift_patches[i].arg;
		u32 *insn = (u32 *)((unsigned long)bd_exec + off);
		u32 w = *insn;

		if (kind == BD_LIFT_PATCH_ADRP) {
			unsigned long insn_page = (unsigned long)insn & ~0xfffUL;
			unsigned long tgt_page = bd_page_addr(arg);

			if (!tgt_page) {
				pr_err("bd1860: adrp target %#x unmapped\n", arg);
				return -EINVAL;
			}
			tgt_page &= ~0xfffUL;
			{
				long imm = (long)(tgt_page - insn_page) >> 12;
				u32 rd = w & 0x1f;

				w = 0x90000000 |
				    (((u32)(imm & 0x3) << 29)) |
				    ((((u32)imm >> 2) & 0x7ffff) << 5) |
				    rd;
				*insn = w;
			}
		} else if (kind == BD_LIFT_PATCH_BL) {
			unsigned idx = arg >> 1;
			unsigned long stub = tramp + idx * 16;
			long delta = (long)(stub - (unsigned long)insn) >> 2;

			if (delta < -(1L << 25) || delta >= (1L << 25)) {
				pr_err("bd1860: bl stub out of range\n");
				return -EINVAL;
			}
			*insn = 0x94000000 | ((u32)delta & 0x3ffffffu);
		} else {
			pr_err("bd1860: unknown patch kind %u\n", kind);
			return -EINVAL;
		}
	}
	flush_icache_range((unsigned long)bd_exec,
			   (unsigned long)bd_exec + bd_exec_len);
	return 0;
}

/* ---- lifted function prototypes (from stock disassembly) ---- */
typedef u8 (*fn_heartbp_init_t)(void);
typedef u8 (*fn_sensor_init_t)(u32 mode, u8 *led3);
typedef u8 (*fn_sensor_start_t)(u32 mode, u32 *cfg3);
typedef u8 (*fn_sensor_close_t)(void);
typedef u8 (*fn_data_read_t)(u32 mode, u16 *frame);
typedef u8 (*fn_health_pro_t)(u32 mode, u8 flag, void *unk,
			      u16 *frame, u32 *result);

#define LIFTED(fo) ((void *)((unsigned long)bd_exec + ((fo) - BD_SPAN_LO)))

/* minimal fwlink: lifted i2c helpers resolve client via
 *   g_data[0] -> fwlink; fwlink+0x10 -> i2c_client (->adapter at +0x18)
 */
struct bd_fwlink {
	u64 _0;
	u64 _8;
	struct i2c_client *client;	/* +0x10 */
	struct input_dev *input;	/* +0x18 (unused by our path) */
};

struct bd_priv {
	struct i2c_client *client;
	struct input_dev *input;
	struct class *cls;
	struct device *clsdev;
	struct task_struct *thread;
	struct mutex lock;
	wait_queue_head_t wq;
	bool enabled;
	u32 mode;
	struct bd_fwlink *fw;
	u16 frame[40];
	u32 result[32];
	u32 cfg[4];
	int err_cnt;
	u32 last_report[5];
	/* debug counters for the lifted Data_Read outcome */
	unsigned long n0, n1, n2;
	u8 last_dr;
	u8 last_hp;		/* last health_pro return */
};

static struct bd_priv *bd;

static void bd_fw_setup(struct bd_priv *st)
{
	u64 *gdata0 = (u64 *)((unsigned long)bd_bss + 0 * 4096 + 0x9e8);

	st->fw->_0 = 0;
	st->fw->_8 = 0;
	st->fw->client = st->client;
	st->fw->input = st->input;
	*gdata0 = (u64)st->fw;
}

static int bd_do_enable(struct bd_priv *st, u32 mode)
{
	fn_sensor_init_t p_init = LIFTED(0x56e104);
	fn_sensor_start_t p_start = LIFTED(0x56fb08);
	u8 led[4] = { 0x05, 0x00, 0x02, 0x00 };
	u8 r1, r2;

	/* stock init_start per-mode LED bytes (regs 0x14/0x15/0x16) */
	if (mode == 2)
		led[0] = 0x00, led[1] = 0x08, led[2] = 0x08;
	else if (mode == 13)
		led[0] = 0x00, led[1] = 0x00, led[2] = 0x02;
	else
		led[0] = 0x05, led[1] = 0x00, led[2] = 0x02;

	/* stock init_start per-mode bp/wear thresholds; Sensor_Start stores
	 * them as wear_ref1/2/3 — zeros would break wear detection */
	if (mode == 2)
		st->cfg[0] = 0x2710, st->cfg[1] = 0x7530, st->cfg[2] = 0x1770;
	else if (mode == 13)
		st->cfg[0] = 0x5dc, st->cfg[1] = 0x1f4, st->cfg[2] = 0xa;
	else
		st->cfg[0] = 0x5dc, st->cfg[1] = 0x64, st->cfg[2] = 5;

	memset(st->frame, 0, sizeof(st->frame));
	memset(st->result, 0, sizeof(st->result));
	st->err_cnt = 0;

	r1 = p_init(mode, led);
	r2 = p_start(mode, st->cfg);
	pr_info("bd1860: Sensor_Init(%u)=%u Sensor_Start=%u\n", mode, r1, r2);
	if (!r1 || !r2)
		pr_err("bd1860: stock init/start reports fail (continuing)\n");
	/* stock hrenable_store stores the mode into the global test_kinds
	 * (bss 0x143a9f0); the lifted code reads it there */
	*(u32 *)((unsigned long)bd_bss + 0 * 4096 + 0x9f0) = mode;
	wake_up_interruptible(&st->wq);
	st->mode = mode;
	st->enabled = true;
	return 0;
}

static void bd_do_disable(struct bd_priv *st)
{
	fn_sensor_close_t p_close = LIFTED(0x57030c);

	p_close();
	st->enabled = false;
}

/* lifted globals of interest (arena = bd_bss, page base + offset) */
static void bd_dump_state(struct bd_priv *st)
{
	u8 *b = bd_bss;
	u8 phdc = *(u8 *)(b + 0x3000 + 0x5bc);
	u8 setflag = *(u8 *)(b + 0x3000 + 0x662);
	u8 hwflag = *(u8 *)(b + 0xae8);
	u32 tk = *(u32 *)(b + 0x9f0);
	u32 raw0 = *(u32 *)(b + 0x3000 + 0x668);
	u32 rawb0 = *(u32 *)(b + 0x3000 + 0x6d0);
	u32 suma = *(u32 *)(b + 0x3000 + 0x7f0);
	u16 chA0 = *(u16 *)(b + 0x3000 + 0x5c0);
	u16 chA1 = *(u16 *)(b + 0x3000 + 0x5c2);
	u16 chB0 = *(u16 *)(b + 0x3000 + 0x5f8);
	struct i2c_client *c = st->client;
	int r07, r27, r2e;

	r07 = i2c_smbus_read_byte_data(c, 0x07);
	r27 = i2c_smbus_read_byte_data(c, 0x27);
	r2e = i2c_smbus_read_byte_data(c, 0x2e);
	pr_info("bd1860 dbg: dr 0=%lu 1=%lu 2=%lu last=%u | tk=%u hw=%u phdc=%u setfl=%u\n",
		st->n0, st->n1, st->n2, st->last_dr, tk, hwflag, phdc,
		setflag);
	pr_info("bd1860 dbg: rawA0=%u rawB0=%u sumA=%u chA=%u,%u chB=%u\n",
		raw0, rawb0, suma, chA0, chA1, chB0);
	pr_info("bd1860 dbg: chip r07=%02x r27=%02x r2e=%02x\n",
		r07 < 0 ? 0xff : r07, r27 < 0 ? 0xff : r27,
		r2e < 0 ? 0xff : r2e);
	pr_info("bd1860 dbg: hp_ret=%u result=%u %u %u %u %u %u\n",
		st->last_hp, st->result[0], st->result[1], st->result[2],
		st->result[3], st->result[4], st->result[5]);
}

static int bd_thread(void *data)
{
	struct bd_priv *st = data;
	fn_data_read_t p_dr = LIFTED(0x570398);
	fn_health_pro_t p_hp = LIFTED(0x58188c);
	int stat = 0;

	while (!kthread_should_stop()) {
		u8 dr;
		u32 mode;

		if (!st->enabled) {
			wait_event_interruptible(st->wq,
						 st->enabled || kthread_should_stop());
			continue;
		}
		mutex_lock(&st->lock);
		if (!st->enabled) {
			mutex_unlock(&st->lock);
			continue;
		}
		if (++stat >= 200) {
			stat = 0;
			bd_dump_state(st);
		}
		mode = st->mode;
		dr = p_dr(mode, st->frame);
		st->last_dr = dr;
		if (dr == 1) {
			int i;

			st->n1++;
			kernel_neon_begin();
			st->last_hp = p_hp(mode, 0, NULL, st->frame,
					   st->result);
			kernel_neon_end();
			/* stock dataread reports result[0..4] every full
			 * frame unconditionally — no confidence gate */
			for (i = 0; i < 5; i++) {
				input_event(st->input, EV_REL, i,
					    st->result[i]);
				st->last_report[i] = st->result[i];
			}
			input_sync(st->input);
		} else if (dr == 2) {
			st->n2++;
			st->err_cnt++;
		} else {
			st->n0++;
		}
		mutex_unlock(&st->lock);
		usleep_range(18000, 22000);
	}
	return 0;
}

static ssize_t hrenable_show(struct device *d, struct device_attribute *a,
			     char *b)
{
	return sprintf(b, "%d\n", bd && bd->enabled);
}

static ssize_t hrenable_store(struct device *d, struct device_attribute *a,
			      const char *b, size_t c)
{
	static const int tbl[6] = { 0, 6, 2, 6, 13, 3 };
	int ch, v;

	if (!bd || c < 1)
		return -EINVAL;
	ch = (unsigned char)b[0];
	if (ch <= 5 && c == 1)
		v = tbl[ch];
	else if (ch >= '0' && ch <= '5')
		v = tbl[ch - '0'];
	else
		return -EINVAL;

	mutex_lock(&bd->lock);
	if (v == 0) {
		if (bd->enabled)
			bd_do_disable(bd);
	} else {
		if (!bd->enabled || bd->mode != (u32)v)
			bd_do_enable(bd, (u32)v);
	}
	mutex_unlock(&bd->lock);
	dev_info(d, "bd1860 lifted hrenable -> mode %d (enabled=%d)\n",
		 v, bd->enabled);
	return c;
}

static struct device_attribute dev_attr_hrenable = {
	.attr = { .name = "hrenable", .mode = 0666 },
	.show = hrenable_show,
	.store = hrenable_store,
};

static ssize_t hrtest_show(struct device *d, struct device_attribute *a,
			   char *b)
{
	if (!bd)
		return sprintf(b, "lifted: not probed\n");
	return sprintf(b, "lifted en=%d mode=%u hr=%u sbp=%u dbp=%u spo2=%u wear=%u err=%d\n",
		       bd->enabled, bd->mode, bd->last_report[0],
		       bd->last_report[1], bd->last_report[2],
		       bd->last_report[3], bd->last_report[4], bd->err_cnt);
}

static ssize_t hrtest_store(struct device *d, struct device_attribute *a,
			    const char *b, size_t c)
{
	int i;

	if (!bd)
		return c;
	dev_info(d, "hrtest lifted: en=%d mode=%u\n", bd->enabled, bd->mode);
	dev_info(d, "hrtest lifted: result=%u %u %u %u %u err=%d\n",
		 bd->last_report[0], bd->last_report[1], bd->last_report[2],
		 bd->last_report[3], bd->last_report[4], bd->err_cnt);
	for (i = 0; i < 8; i++)
		dev_info(d, "hrtest lifted: frame[%d]=%u\n", i, bd->frame[i]);
	bd_dump_state(bd);
	return c;
}

static struct device_attribute dev_attr_hrtest = {
	.attr = { .name = "hrtest", .mode = 0644 },
	.show = hrtest_show,
	.store = hrtest_store,
};

/* stock blob calls __stack_chk_fail when its stack canary is smashed;
 * don't depend on our kernel having one compiled in */
static void bd_stack_chk_fail(void)
{
	panic("bd1860: lifted stack canary smashed\n");
}

static int bd_setup_lift(void)
{
	int ret;

	bd_api_addrs[BD_API___CONST_UDELAY] = __const_udelay;
	bd_api_addrs[BD_API___INIT_WAITQUEUE_HEAD] = __init_waitqueue_head;
	bd_api_addrs[BD_API___STACK_CHK_FAIL] = bd_stack_chk_fail;
	bd_api_addrs[BD_API_COMPLETE] = complete;
	bd_api_addrs[BD_API_DEV_ERR] = dev_err;
	bd_api_addrs[BD_API_DEV_WARN] = dev_warn;
	bd_api_addrs[BD_API_I2C_RECOVER_BUS] = i2c_recover_bus;
	bd_api_addrs[BD_API_I2C_SMBUS_READ_I2C_BLOCK_DATA] =
		i2c_smbus_read_i2c_block_data;
	bd_api_addrs[BD_API_I2C_TRANSFER] = i2c_transfer;
	bd_api_addrs[BD_API_INPUT_EVENT] = input_event;
	bd_api_addrs[BD_API_KTHREAD_CREATE_ON_NODE] = kthread_create_on_node;
	bd_api_addrs[BD_API_KTHREAD_SHOULD_STOP] = kthread_should_stop;
	bd_api_addrs[BD_API_KTHREAD_STOP] = kthread_stop;
	bd_api_addrs[BD_API_MEMSET] = memset;
	bd_api_addrs[BD_API_MSLEEP] = msleep;
	bd_api_addrs[BD_API_PRINTK] = printk;
	bd_api_addrs[BD_API_USLEEP_RANGE] = usleep_range;
	bd_api_addrs[BD_API_WAKE_UP_PROCESS] = wake_up_process;

	bd_exec_len = ALIGN(BD_LIFT_BLOB_LEN, 8) + BD_API_MAX * 16;
	bd_exec = __vmalloc(bd_exec_len, GFP_KERNEL, PAGE_KERNEL_EXEC);
	if (!bd_exec)
		return -ENOMEM;
	memcpy(bd_exec, bd_blob, BD_LIFT_BLOB_LEN);

	bd_ro = vzalloc(BD_RO_N * 4096);
	bd_bss = vzalloc(BD_BSS_N * 4096);
	if (!bd_ro || !bd_bss) {
		ret = -ENOMEM;
		goto err;
	}
	{
		int i;

		for (i = 0; i < BD_RO_N; i++)
			memcpy((u8 *)bd_ro + i * 4096, bd_ro_data[i], 4096);
	}
	ret = bd_apply_patches();
	if (ret)
		goto err;
	pr_info("bd1860: lifted blob ready (exec %lu bytes, %lu patches)\n",
		bd_exec_len, (unsigned long)ARRAY_SIZE(bd_lift_patches));
	return 0;
err:
	if (bd_ro) {
		vfree(bd_ro);
		bd_ro = NULL;
	}
	if (bd_bss) {
		vfree(bd_bss);
		bd_bss = NULL;
	}
	if (bd_exec) {
		vfree(bd_exec);
		bd_exec = NULL;
	}
	return ret;
}

static int bd_probe(struct i2c_client *client, const struct i2c_device_id *id)
{
	struct device *dev = &client->dev;
	struct bd_priv *st;
	fn_heartbp_init_t p_hb;
	int ret;

	dev_info(dev, "bd1860 lifted probe\n");
	if (bd) {
		dev_err(dev, "already probed\n");
		return -EBUSY;
	}
	ret = bd_setup_lift();
	if (ret)
		return ret;

	st = devm_kzalloc(dev, sizeof(*st), GFP_KERNEL);
	if (!st)
		return -ENOMEM;
	st->client = client;
	mutex_init(&st->lock);
	init_waitqueue_head(&st->wq);

	st->fw = devm_kzalloc(dev, sizeof(*st->fw), GFP_KERNEL);
	if (!st->fw)
		return -ENOMEM;

	st->input = devm_input_allocate_device(dev);
	if (!st->input)
		return -ENOMEM;
	st->input->name = "bd1860";
	st->input->id.bustype = BUS_I2C;
	input_set_capability(st->input, EV_REL, REL_X);
	input_set_capability(st->input, EV_REL, REL_Y);
	input_set_capability(st->input, EV_REL, REL_Z);
	input_set_capability(st->input, EV_REL, REL_RX);
	input_set_capability(st->input, EV_REL, REL_RY);
	input_set_capability(st->input, EV_REL, REL_RZ);
	ret = input_register_device(st->input);
	if (ret)
		return ret;

	st->cls = NULL;
	st->clsdev = NULL;
	/* class/device + sysfs below */
	st->cls = class_create(THIS_MODULE, "bd1860");
	if (IS_ERR(st->cls))
		return PTR_ERR(st->cls);
	st->clsdev = device_create(st->cls, dev, MKDEV(0, 0), st, "device");
	if (IS_ERR(st->clsdev)) {
		ret = PTR_ERR(st->clsdev);
		goto err_class;
	}
	ret = device_create_file(st->clsdev, &dev_attr_hrenable);
	if (ret)
		goto err_dev;
	ret = device_create_file(st->clsdev, &dev_attr_hrtest);
	if (ret)
		goto err_hren;

	bd_fw_setup(st);
	bd = st;

	p_hb = LIFTED(0x56e024);
	p_hb();
	dev_info(dev, "bd1860 lifted: heartbp_init done\n");

	st->thread = kthread_run(bd_thread, st, "bd1860-lift");
	if (IS_ERR(st->thread)) {
		ret = PTR_ERR(st->thread);
		st->thread = NULL;
		goto err_hr;
	}

	i2c_set_clientdata(client, st);
	dev_info(dev, "bd1860 lifted ready\n");
	return 0;

err_hr:
	device_remove_file(st->clsdev, &dev_attr_hrtest);
err_hren:
	device_remove_file(st->clsdev, &dev_attr_hrenable);
err_dev:
	device_destroy(st->cls, MKDEV(0, 0));
err_class:
	class_destroy(st->cls);
	bd = NULL;
	return ret;
}

static int bd_remove(struct i2c_client *client)
{
	struct bd_priv *st = i2c_get_clientdata(client);

	if (st->thread) {
		wake_up_interruptible(&st->wq);
		kthread_stop(st->thread);
	}
	mutex_lock(&st->lock);
	if (st->enabled)
		bd_do_disable(st);
	mutex_unlock(&st->lock);
	device_remove_file(st->clsdev, &dev_attr_hrtest);
	device_remove_file(st->clsdev, &dev_attr_hrenable);
	device_destroy(st->cls, MKDEV(0, 0));
	class_destroy(st->cls);
	if (bd == st)
		bd = NULL;
	return 0;
}

static const struct of_device_id bd_of[] = {
	{ .compatible = "bd,bd1860" },
	{}
};
MODULE_DEVICE_TABLE(of, bd_of);

static const struct i2c_device_id bd_id[] = {
	{ "bd1860", 0 },
	{}
};
MODULE_DEVICE_TABLE(i2c, bd_id);

static struct i2c_driver bd_drv = {
	.driver = {
		.name = "bd1860",
		.of_match_table = bd_of,
	},
	.probe = bd_probe,
	.remove = bd_remove,
	.id_table = bd_id,
};
module_i2c_driver(bd_drv);
MODULE_AUTHOR("Kokuban");
MODULE_DESCRIPTION("UWS6152 bd1860 lifted stock driver+algorithm");
MODULE_LICENSE("GPL");
