obj-$(CONFIG_DEVFREQ_SPRD_AUTO_DFS)     += sprd_dfs_auto_drv.o
obj-$(CONFIG_DEVFREQ_GOV_SPRD_SCENE)     += sprd_scene_governor.o
ccflags-y += -I$(srctree) -I$(srctree)/drivers/devfreq/sprd
CFLAGS_sprd_dfs_auto_drv.o := -I$(src)
CFLAGS_sprd_scene_governor.o := -I$(src)
